// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['poisson.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef;

extern ufc_finite_element element_07fa8f5964363dd58f6c7669235ca907d3b8aa62;

extern ufc_dofmap dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef;

extern ufc_dofmap dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62;

extern ufc_integral integral_543b52043fdd412b9e60635ed0c6b396cf36ec15;

extern ufc_integral integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a;

extern ufc_form form_1285b66645912deba655203e7947b79f65798a37;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_poisson_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_poisson_a(const char* function_name);

extern ufc_form form_bf3449ca17a209550fd4926f9139272049e7d18e;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_poisson_L;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_poisson_L(const char* function_name);

#ifdef __cplusplus
}
#endif
