// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['poisson.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef





ufc_finite_element element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 1)",
  .cell_shape = tetrahedron,
  .element_type = ufc_basix_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "Lagrange",

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef

// Code for element element_07fa8f5964363dd58f6c7669235ca907d3b8aa62

int value_shape_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62[1] = { 3 };
int reference_value_shape_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62[1] = { 3 };
ufc_finite_element* sub_elements_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62[3] = { &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };

ufc_finite_element element_07fa8f5964363dd58f6c7669235ca907d3b8aa62 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .cell_shape = tetrahedron,
  .element_type = ufc_blocked_element,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .reference_value_size = 3,
  .degree = 1,
  .block_size = 3,
  .family = "Lagrange",

  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_07fa8f5964363dd58f6c7669235ca907d3b8aa62
};

// End of code for element element_07fa8f5964363dd58f6c7669235ca907d3b8aa62

// Code for dofmap dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef



void tabulate_entity_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 2;
        dofs[1] = 3;
        break;
    case 1:
        dofs[0] = 1;
        dofs[1] = 3;
        break;
    case 2:
        dofs[0] = 1;
        dofs[1] = 2;
        break;
    case 3:
        dofs[0] = 0;
        dofs[1] = 3;
        break;
    case 4:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 5:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 1;
        dofs[1] = 2;
        dofs[2] = 3;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        dofs[2] = 3;
        break;
    case 2:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 3;
        break;
    case 3:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        break;
    }
    break;
case 3:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef[4] = { 1, 2, 3, 4 };

ufc_dofmap dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef

// Code for dofmap dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62

ufc_dofmap* sub_dofmaps_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62[3] = { &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };

void tabulate_entity_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 2;
        dofs[1] = 3;
        break;
    case 1:
        dofs[0] = 1;
        dofs[1] = 3;
        break;
    case 2:
        dofs[0] = 1;
        dofs[1] = 2;
        break;
    case 3:
        dofs[0] = 0;
        dofs[1] = 3;
        break;
    case 4:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 5:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 1;
        dofs[1] = 2;
        dofs[2] = 3;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        dofs[2] = 3;
        break;
    case 2:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 3;
        break;
    case 3:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        break;
    }
    break;
case 3:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        dofs[3] = 3;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62[4] = { 1, 2, 3, 4 };

ufc_dofmap dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .block_size = 3,
  .num_entity_dofs = num_entity_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62
};

// End of code for dofmap dofmap_07fa8f5964363dd58f6c7669235ca907d3b8aa62

// Code for integral integral_543b52043fdd412b9e60635ed0c6b396cf36ec15

void tabulate_tensor_integral_543b52043fdd412b9e60635ed0c6b396cf36ec15(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_421[1] = { 0.1666666666666667 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_D100_Q421[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE9_C1_D010_Q421[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Q421[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule 421
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Q421[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Q421[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Q421[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Q421[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Q421[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Q421[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Q421[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Q421[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Q421[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Q421[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Q421[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Q421[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Q421[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Q421[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Q421[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Q421[0][0][0][3];
    const double J_c0 = coordinate_dofs[0] * FE8_C0_D100_Q421[0][0][0][0] + coordinate_dofs[3] * FE8_C0_D100_Q421[0][0][0][1] + coordinate_dofs[6] * FE8_C0_D100_Q421[0][0][0][2] + coordinate_dofs[9] * FE8_C0_D100_Q421[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Q421[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Q421[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Q421[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Q421[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE8_C0_D100_Q421[0][0][0][0] + coordinate_dofs[5] * FE8_C0_D100_Q421[0][0][0][1] + coordinate_dofs[8] * FE8_C0_D100_Q421[0][0][0][2] + coordinate_dofs[11] * FE8_C0_D100_Q421[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE8_C0_D100_Q421[0][0][0][0] + coordinate_dofs[4] * FE8_C0_D100_Q421[0][0][0][1] + coordinate_dofs[7] * FE8_C0_D100_Q421[0][0][0][2] + coordinate_dofs[10] * FE8_C0_D100_Q421[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Q421[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Q421[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Q421[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Q421[0][0][0][3];
    ufc_scalar_t sp_421[80];
    sp_421[0] = J_c4 * J_c8;
    sp_421[1] = J_c5 * J_c7;
    sp_421[2] = sp_421[0] + -1 * sp_421[1];
    sp_421[3] = J_c0 * sp_421[2];
    sp_421[4] = J_c5 * J_c6;
    sp_421[5] = J_c3 * J_c8;
    sp_421[6] = sp_421[4] + -1 * sp_421[5];
    sp_421[7] = J_c1 * sp_421[6];
    sp_421[8] = sp_421[3] + sp_421[7];
    sp_421[9] = J_c3 * J_c7;
    sp_421[10] = J_c4 * J_c6;
    sp_421[11] = sp_421[9] + -1 * sp_421[10];
    sp_421[12] = J_c2 * sp_421[11];
    sp_421[13] = sp_421[8] + sp_421[12];
    sp_421[14] = sp_421[2] / sp_421[13];
    sp_421[15] = J_c3 * (-1 * J_c8);
    sp_421[16] = sp_421[4] + sp_421[15];
    sp_421[17] = sp_421[16] / sp_421[13];
    sp_421[18] = sp_421[11] / sp_421[13];
    sp_421[19] = sp_421[14] * sp_421[14];
    sp_421[20] = sp_421[14] * sp_421[17];
    sp_421[21] = sp_421[18] * sp_421[14];
    sp_421[22] = sp_421[17] * sp_421[17];
    sp_421[23] = sp_421[18] * sp_421[17];
    sp_421[24] = sp_421[18] * sp_421[18];
    sp_421[25] = J_c2 * J_c7;
    sp_421[26] = J_c8 * (-1 * J_c1);
    sp_421[27] = sp_421[25] + sp_421[26];
    sp_421[28] = sp_421[27] / sp_421[13];
    sp_421[29] = J_c0 * J_c8;
    sp_421[30] = J_c6 * (-1 * J_c2);
    sp_421[31] = sp_421[29] + sp_421[30];
    sp_421[32] = sp_421[31] / sp_421[13];
    sp_421[33] = J_c1 * J_c6;
    sp_421[34] = J_c0 * J_c7;
    sp_421[35] = sp_421[33] + -1 * sp_421[34];
    sp_421[36] = sp_421[35] / sp_421[13];
    sp_421[37] = sp_421[28] * sp_421[28];
    sp_421[38] = sp_421[28] * sp_421[32];
    sp_421[39] = sp_421[28] * sp_421[36];
    sp_421[40] = sp_421[32] * sp_421[32];
    sp_421[41] = sp_421[32] * sp_421[36];
    sp_421[42] = sp_421[36] * sp_421[36];
    sp_421[43] = sp_421[37] + sp_421[19];
    sp_421[44] = sp_421[38] + sp_421[20];
    sp_421[45] = sp_421[39] + sp_421[21];
    sp_421[46] = sp_421[40] + sp_421[22];
    sp_421[47] = sp_421[41] + sp_421[23];
    sp_421[48] = sp_421[24] + sp_421[42];
    sp_421[49] = J_c1 * J_c5;
    sp_421[50] = J_c2 * J_c4;
    sp_421[51] = sp_421[49] + -1 * sp_421[50];
    sp_421[52] = sp_421[51] / sp_421[13];
    sp_421[53] = J_c2 * J_c3;
    sp_421[54] = J_c0 * J_c5;
    sp_421[55] = sp_421[53] + -1 * sp_421[54];
    sp_421[56] = sp_421[55] / sp_421[13];
    sp_421[57] = J_c0 * J_c4;
    sp_421[58] = J_c1 * J_c3;
    sp_421[59] = sp_421[57] + -1 * sp_421[58];
    sp_421[60] = sp_421[59] / sp_421[13];
    sp_421[61] = sp_421[52] * sp_421[52];
    sp_421[62] = sp_421[52] * sp_421[56];
    sp_421[63] = sp_421[60] * sp_421[52];
    sp_421[64] = sp_421[56] * sp_421[56];
    sp_421[65] = sp_421[60] * sp_421[56];
    sp_421[66] = sp_421[60] * sp_421[60];
    sp_421[67] = sp_421[43] + sp_421[61];
    sp_421[68] = sp_421[44] + sp_421[62];
    sp_421[69] = sp_421[45] + sp_421[63];
    sp_421[70] = sp_421[46] + sp_421[64];
    sp_421[71] = sp_421[47] + sp_421[65];
    sp_421[72] = sp_421[48] + sp_421[66];
    sp_421[73] = fabs(sp_421[13]);
    sp_421[74] = sp_421[67] * sp_421[73];
    sp_421[75] = sp_421[68] * sp_421[73];
    sp_421[76] = sp_421[69] * sp_421[73];
    sp_421[77] = sp_421[70] * sp_421[73];
    sp_421[78] = sp_421[71] * sp_421[73];
    sp_421[79] = sp_421[72] * sp_421[73];
    for (int iq = 0; iq < 1; ++iq)
    {
        const ufc_scalar_t fw0 = sp_421[74] * weights_421[iq];
        const ufc_scalar_t fw1 = sp_421[75] * weights_421[iq];
        const ufc_scalar_t fw2 = sp_421[76] * weights_421[iq];
        const ufc_scalar_t fw3 = sp_421[77] * weights_421[iq];
        const ufc_scalar_t fw4 = sp_421[78] * weights_421[iq];
        const ufc_scalar_t fw5 = sp_421[79] * weights_421[iq];
        ufc_scalar_t t0[4];
        ufc_scalar_t t1[4];
        ufc_scalar_t t2[4];
        for (int i = 0; i < 4; ++i)
        {
            t0[i] = fw0 * FE8_C0_D100_Q421[0][0][0][i] + fw1 * FE9_C1_D010_Q421[0][0][0][i] + fw2 * FE9_C2_D001_Q421[0][0][0][i];
            t1[i] = fw1 * FE8_C0_D100_Q421[0][0][0][i] + fw3 * FE9_C1_D010_Q421[0][0][0][i] + fw4 * FE9_C2_D001_Q421[0][0][0][i];
            t2[i] = fw2 * FE8_C0_D100_Q421[0][0][0][i] + fw4 * FE9_C1_D010_Q421[0][0][0][i] + fw5 * FE9_C2_D001_Q421[0][0][0][i];
        }
        for (int i = 0; i < 4; ++i)
        {
            for (int j = 0; j < 4; ++j)
            {
                ufc_scalar_t acc0 = 0;
                acc0 += FE8_C0_D100_Q421[0][0][0][j] * t0[i];
                acc0 += FE9_C1_D010_Q421[0][0][0][j] * t1[i];
                acc0 += FE9_C2_D001_Q421[0][0][0][j] * t2[i];
                A[4 * i + j] += acc0;
            }
        }
    }
}



ufc_integral integral_543b52043fdd412b9e60635ed0c6b396cf36ec15 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_543b52043fdd412b9e60635ed0c6b396cf36ec15,
};

// End of code for integral integral_543b52043fdd412b9e60635ed0c6b396cf36ec15

// Code for integral integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a

void tabulate_tensor_integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_fad[4] = { 0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE8_C0_Qfad[1][1][4][4] =
        { { { { 0.1381966011250091, 0.5854101966249688, 0.138196601125011, 0.1381966011250109 },
              { 0.1381966011250091, 0.1381966011250109, 0.5854101966249688, 0.1381966011250109 },
              { 0.1381966011250091, 0.138196601125011, 0.1381966011250111, 0.5854101966249691 },
              { 0.585410196624967, 0.1381966011250109, 0.138196601125011, 0.1381966011250109 } } } };
    static const double FE9_C0_D100_Qfad[1][1][1][4] = { { { { -1.0, 1.0, 0.0, 0.0 } } } };
    static const double FE9_C1_D010_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 1.0, 0.0 } } } };
    static const double FE9_C2_D001_Qfad[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule fad
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c4 = coordinate_dofs[1] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c8 = coordinate_dofs[2] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C2_D001_Qfad[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c1 = coordinate_dofs[0] * FE9_C1_D010_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C1_D010_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C1_D010_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C1_D010_Qfad[0][0][0][3];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Qfad[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Qfad[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D100_Qfad[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D100_Qfad[0][0][0][3];
    const double J_c2 = coordinate_dofs[0] * FE9_C2_D001_Qfad[0][0][0][0] + coordinate_dofs[3] * FE9_C2_D001_Qfad[0][0][0][1] + coordinate_dofs[6] * FE9_C2_D001_Qfad[0][0][0][2] + coordinate_dofs[9] * FE9_C2_D001_Qfad[0][0][0][3];
    ufc_scalar_t sp_fad[15];
    sp_fad[0] = J_c4 * J_c8;
    sp_fad[1] = J_c5 * J_c7;
    sp_fad[2] = sp_fad[0] + -1 * sp_fad[1];
    sp_fad[3] = J_c0 * sp_fad[2];
    sp_fad[4] = J_c5 * J_c6;
    sp_fad[5] = J_c3 * J_c8;
    sp_fad[6] = sp_fad[4] + -1 * sp_fad[5];
    sp_fad[7] = J_c1 * sp_fad[6];
    sp_fad[8] = sp_fad[3] + sp_fad[7];
    sp_fad[9] = J_c3 * J_c7;
    sp_fad[10] = J_c4 * J_c6;
    sp_fad[11] = sp_fad[9] + -1 * sp_fad[10];
    sp_fad[12] = J_c2 * sp_fad[11];
    sp_fad[13] = sp_fad[8] + sp_fad[12];
    sp_fad[14] = fabs(sp_fad[13]);
    for (int iq = 0; iq < 4; ++iq)
    {
        // Quadrature loop body setup for quadrature rule fad
        // Varying computations for quadrature rule fad
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 4; ++ic)
            w0 += w[ic] * FE8_C0_Qfad[0][0][iq][ic];
        ufc_scalar_t sv_fad[1];
        sv_fad[0] = sp_fad[14] * w0;
        const ufc_scalar_t fw0 = sv_fad[0] * weights_fad[iq];
        for (int i = 0; i < 4; ++i)
            A[i] += fw0 * FE8_C0_Qfad[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a[1] = { false };

ufc_integral integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a =
{
  .enabled_coefficients = enabled_coefficients_integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a,
  .tabulate_tensor = tabulate_tensor_integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a,
};

// End of code for integral integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a

// Code for form form_1285b66645912deba655203e7947b79f65798a37


ufc_dofmap* dofmaps_form_1285b66645912deba655203e7947b79f65798a37[2] = { &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };
ufc_finite_element* finite_elements_form_1285b66645912deba655203e7947b79f65798a37[2] = { &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };

// Return a list of the coefficient names.
const char** coefficient_name_form_1285b66645912deba655203e7947b79f65798a37(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_1285b66645912deba655203e7947b79f65798a37(void)
{
return NULL;
}

int* integral_ids_form_1285b66645912deba655203e7947b79f65798a37(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_1285b66645912deba655203e7947b79f65798a37[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_1285b66645912deba655203e7947b79f65798a37;
default:
    return NULL;
}
}

int num_integrals_form_1285b66645912deba655203e7947b79f65798a37(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_1285b66645912deba655203e7947b79f65798a37(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_1285b66645912deba655203e7947b79f65798a37[1] = { &integral_543b52043fdd412b9e60635ed0c6b396cf36ec15 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_1285b66645912deba655203e7947b79f65798a37;
default:
    return NULL;
}
}

ufc_form form_1285b66645912deba655203e7947b79f65798a37 =
{

  .signature = "a4bfe56d456282b252665ff416d395c3487df4a19188830c511c169c360cd953886e4a17e40c4085b0b3c619474987b1b91f13b4eca9859bee0dfe00da9d3b48",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_1285b66645912deba655203e7947b79f65798a37,
  .constant_name_map = constant_name_form_1285b66645912deba655203e7947b79f65798a37,

  .finite_elements = finite_elements_form_1285b66645912deba655203e7947b79f65798a37,
  .dofmaps = dofmaps_form_1285b66645912deba655203e7947b79f65798a37,

  .integral_ids = integral_ids_form_1285b66645912deba655203e7947b79f65798a37,
  .num_integrals = num_integrals_form_1285b66645912deba655203e7947b79f65798a37,

  .integrals = integrals_form_1285b66645912deba655203e7947b79f65798a37
};

// Alias name
ufc_form* form_poisson_a = &form_1285b66645912deba655203e7947b79f65798a37;

ufc_function_space* functionspace_form_poisson_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.dofmap = &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.dofmap = &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_1285b66645912deba655203e7947b79f65798a37

// Code for form form_bf3449ca17a209550fd4926f9139272049e7d18e

int original_coefficient_position_form_bf3449ca17a209550fd4926f9139272049e7d18e[1] = { 0 };
ufc_dofmap* dofmaps_form_bf3449ca17a209550fd4926f9139272049e7d18e[2] = { &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };
ufc_finite_element* finite_elements_form_bf3449ca17a209550fd4926f9139272049e7d18e[2] = { &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef, &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef };

// Return a list of the coefficient names.
const char** coefficient_name_form_bf3449ca17a209550fd4926f9139272049e7d18e(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_bf3449ca17a209550fd4926f9139272049e7d18e(void)
{
return NULL;
}

int* integral_ids_form_bf3449ca17a209550fd4926f9139272049e7d18e(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_bf3449ca17a209550fd4926f9139272049e7d18e[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_bf3449ca17a209550fd4926f9139272049e7d18e;
default:
    return NULL;
}
}

int num_integrals_form_bf3449ca17a209550fd4926f9139272049e7d18e(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_bf3449ca17a209550fd4926f9139272049e7d18e(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_bf3449ca17a209550fd4926f9139272049e7d18e[1] = { &integral_d82d3d0f3978e7ea9277e54e88dcf89a87e81b8a };
switch (integral_type)
{
case cell:
    return integrals_cell_form_bf3449ca17a209550fd4926f9139272049e7d18e;
default:
    return NULL;
}
}

ufc_form form_bf3449ca17a209550fd4926f9139272049e7d18e =
{

  .signature = "44106fd01405fbd79a786ee9e6b6ca66032a217066d9f7e89d62509a023009da7f35d5d45d512d692f78fb6870e876cb1de1a826ceb3fcbf1de7c735e46b5b08",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_bf3449ca17a209550fd4926f9139272049e7d18e,

  .coefficient_name_map = coefficient_name_form_bf3449ca17a209550fd4926f9139272049e7d18e,
  .constant_name_map = constant_name_form_bf3449ca17a209550fd4926f9139272049e7d18e,

  .finite_elements = finite_elements_form_bf3449ca17a209550fd4926f9139272049e7d18e,
  .dofmaps = dofmaps_form_bf3449ca17a209550fd4926f9139272049e7d18e,

  .integral_ids = integral_ids_form_bf3449ca17a209550fd4926f9139272049e7d18e,
  .num_integrals = num_integrals_form_bf3449ca17a209550fd4926f9139272049e7d18e,

  .integrals = integrals_form_bf3449ca17a209550fd4926f9139272049e7d18e
};

// Alias name
ufc_form* form_poisson_L = &form_bf3449ca17a209550fd4926f9139272049e7d18e;

ufc_function_space* functionspace_form_poisson_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.dofmap = &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_f =
{
.finite_element = &element_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.dofmap = &dofmap_9a4725d1f595a945c7ea37aa8d0209e0c3faf9ef,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "f") == 0)
    return &functionspace_f;
return NULL;

}

// End of code for form form_bf3449ca17a209550fd4926f9139272049e7d18e
